export const ACTIVE_TAB = 'ACTIVE_TAB';

export const LOAD_FILMS = {
    REQUESTED: 'LOAD_FILMS.REQUESTED',
    PENDING: 'LOAD_FILMS.PENDING',
    FAILURE: 'LOAD_FILMS.FAILURE',
    SUCCESS: 'LOAD_FILMS.SUCCESS'
};

export const SHOW_FILM = {
    REQUESTED: 'SHOW_FILM.REQUESTED',
    PENDING: 'SHOW_FILM.PENDING',
    FAILURE: 'SHOW_FILM.FAILURE',
    SUCCESS: 'SHOW_FILM.SUCCESS'
};

export const SORTING_FILMS = {
    REQUESTED: 'SORTING_FILMS.REQUESTED',
    PENDING: 'SORTING_FILMS.PENDING',
    FAILURE: 'SORTING_FILMS.FAILURE',
    SUCCESS: 'SORTING_FILMS.SUCCESS'
};
